<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>errores con callbacks</title>
</head>

<body>
   <script src="https://code.jquery.com/jquery-3.5.1.min.js"
      integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>



   <script>


      //siguiendo con el codigo anterior vamos a hacer un programa que logie los datos de
      //multiples personajes 

      const API_URL = 'https://swapi.dev/api/'
      const PEOPLE_URL = 'people/:id'

      const opts = { crossDomain: true }



      function obtenerPersonaje(id, callback) {
         const url = `${API_URL}${PEOPLE_URL.replace(':id', id)}`

         $.get(url, opts, callback).fail(function(){
            console.log(`sucedio un error  ${id} `)      
         })                                                          //--> EL METODO fail nos ayuda si algun error
      }




     obtenerPersonaje(1, function (personaje) {
         console.log(`hola soy ${personaje.name} `)
         obtenerPersonaje(2, function (personaje) {
            console.log(`hola soy ${personaje.name} `)
            obtenerPersonaje(3, function (personaje) {
               console.log(`hola soy ${personaje.name} `)
               obtenerPersonaje(4, function (personaje) {
                  console.log(`hola soy ${personaje.name} `)
               })
            })
         })
      })

       
   </script>

</body>

</html>